### ISSUE TITLE
rustlib.so: unknown file type

### ISSUE THREAD

**Issue by xchuwenbo** [neurocard/neurocard#2]
Hi there, 

Thanks for your great work!

I am reproducing your codes but cannot import factorized_sampler_lib/rustlib.so. It says:

> ImportError: dlopen(/Users/wbhu/projects/CardEst/neurocard/neurocard/factorized_sampler_lib/rustlib.so, 2): no suitable image found.  Did find:
        /Users/wbhu/projects/CardEst/neurocard/neurocard/factorized_sampler_lib/rustlib.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
        /Users/wbhu/projects/CardEst/neurocard/neurocard/factorized_sampler_lib/rustlib.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

**Comment by frank-lsf** [comment]
What platform (OS, arch) are you using? The `rustlib.so` in this repo is built for x86 Linux. You might need to rebuild the Rust module for your platform.

**Comment by xchuwenbo** [comment]
Seems I wrongly run it on MacOS. It works well on ubuntu. 

Thanks and I will close this comment.
